services:

  simulador:

    build: .

    container_name: simulador_so

    volumes:
      - ./src:/app/src
      - ./inputs:/app/inputs
      - ./outputs:/app/outputs

    command: >
      --alg ALL
      --input inputs/caso_preempcao.json